# Generated by Django 3.0.4 on 2020-04-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
